export default function handler(req, res) {
    res.status(200).json([
        { code: 'CIC0004', displayName: 'ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES', nature: 'OBRIGATORIO', alias: 'APDC', 'period': 1 },
        { code: 'FGA0161', displayName: 'ENGENHARIA E AMBIENTE', nature: 'OBRIGATORIO', alias: 'EA', 'period': 1 },
        { code: 'FGA0163', displayName: 'INTRODUÇÃO À ENGENHARIA', nature: 'OBRIGATORIO', alias: 'IE', 'period': 1 },
        { code: 'FGA0168', displayName: 'DESENHO INDUSTRIAL ASSISTIDO POR COMPUTADOR', nature: 'OBRIGATORIO', alias: 'DIAPC', 'period': 1 },
        { code: 'MAT0025', displayName: 'CÁLCULO 1', nature: 'OBRIGATORIO', alias: 'C', 'period': 1 },
        { code: 'FGA0157', displayName: 'PROBABILIDADE E ESTATÍSTICA APLICADO A ENGENHARIA', nature: 'OBRIGATORIO', alias: 'PEAE', 'period': 2 },
        { code: 'FGA0254', displayName: 'CIÊNCIAS AEROESPACIAIS', nature: 'OBRIGATORIO', alias: 'CA', 'period': 2 },
        { code: 'IFD0171', displayName: 'FISICA 1', nature: 'OBRIGATORIO', alias: 'F', 'period': 2 },
        { code: 'IFD0173', displayName: 'FISICA 1 EXPERIMENTAL', nature: 'OBRIGATORIO', alias: 'FE', 'period': 2 },
        { code: 'MAT0026', displayName: 'CÁLCULO 2', nature: 'OBRIGATORIO', alias: 'C', 'period': 2 },
        { code: 'MAT0031', displayName: 'INTRODUCAO A ALGEBRA LINEAR', nature: 'OBRIGATORIO', alias: 'IAL', 'period': 2 },
        { code: 'FGA0008', displayName: 'SISTEMAS AEROESPACIAIS', nature: 'OBRIGATORIO', alias: 'SA', 'period': 3 },
        { code: 'FGA0133', displayName: 'ENGENHARIA ECONÔMICA', nature: 'OBRIGATORIO', alias: 'EE', 'period': 3 },
        { code: 'FGA0154', displayName: 'MECANICA DOS SÓLIDOS 1 PARA ENGENHARIA', nature: 'OBRIGATORIO', alias: 'MDSPE', 'period': 3 },
        { code: 'FGA0160', displayName: 'MÉTODOS NUMÉRICOS PARA ENGENHARIA', nature: 'OBRIGATORIO', alias: 'MNPE', 'period': 3 },
        { code: 'IQD0125', displayName: 'QUIMICA GERAL TEORICA', nature: 'OBRIGATORIO', alias: 'QGT', 'period': 3 },
        { code: 'IQD0126', displayName: 'QUIMICA GERAL EXPERIMENTAL', nature: 'OBRIGATORIO', alias: 'QGE', 'period': 3 },
        { code: 'MAT0027', displayName: 'CÁLCULO 3', nature: 'OBRIGATORIO', alias: 'C', 'period': 3 },
        { code: 'ENM0080', displayName: 'FENOMENOS DE TRANSPORTE', nature: 'OBRIGATORIO', alias: 'FDT', 'period': 4 },
        { code: 'FGA0102', displayName: 'SINAIS E SISTEMAS PARA ENGENHARIA', nature: 'OBRIGATORIO', alias: 'SSPE', 'period': 4 },
        { code: 'FGA0150', displayName: 'PROJETO INTEGRADOR DE ENGENHARIA 1', nature: 'OBRIGATORIO', alias: 'PIDE', 'period': 4 },
        { code: 'FGA0179', displayName: 'MECANICA DOS SÓLIDOS 2 PARA ENGENHARIA', nature: 'OBRIGATORIO', alias: 'MDSPE', 'period': 4 },
        { code: 'ENM0068', displayName: 'TERMODINAMICA 1', nature: 'OBRIGATORIO', alias: 'T', 'period': 5 },
        { code: 'FGA0075', displayName: 'LABORATÓRIO DE MATERIAIS DE CONSTRUÇÃO', nature: 'OBRIGATORIO', alias: 'LDMDC', 'period': 5 },
        { code: 'FGA0078', displayName: 'TEORIA DE MATERIAIS DE CONSTRUÇÃO', nature: 'OBRIGATORIO', alias: 'TDMDC', 'period': 5 },
        { code: 'FGA0086', displayName: 'TEORIA DE ELETRICIDADE APLICADA', nature: 'OBRIGATORIO', alias: 'TDEA', 'period': 5 },
        { code: 'FGA0087', displayName: 'LABORATÓRIO DE ELETRICIDADE APLICADA', nature: 'OBRIGATORIO', alias: 'LDEA', 'period': 5 },
        { code: 'FGA0119', displayName: 'TEORIA DE ELETROMAGNETISMO', nature: 'OBRIGATORIO', alias: 'TDE', 'period': 5 },
        { code: 'FGA0120', displayName: 'PRÁTICA DE ELETROMAGNETISMO', nature: 'OBRIGATORIO', alias: 'PDE', 'period': 5 },
        { code: 'FGA0204', displayName: 'DINÂMICA DOS FLUÍDOS', nature: 'OBRIGATORIO', alias: 'DDF', 'period': 5 },
        { code: 'ENM0071', displayName: 'TRANSFERENCIA DE CALOR', nature: 'OBRIGATORIO', alias: 'TDC', 'period': 6 },
        { code: 'FGA0038', displayName: 'AERODINÂMICA DE SISTEMAS AEROESPACIAIS', nature: 'OBRIGATORIO', alias: 'ADSA', 'period': 6 },
        { code: 'FGA0164', displayName: 'HUMANIDADES E CIDADANIA', nature: 'OBRIGATORIO', alias: 'HC', 'period': 6 },
        { code: 'FGA0184', displayName: 'GESTÃO DA PRODUÇÃO E QUALIDADE', nature: 'OBRIGATORIO', alias: 'GDPQ', 'period': 6 },
        { code: 'FGA0197', displayName: 'SISTEMAS DE CONTROLE', nature: 'OBRIGATORIO', alias: 'SDC', 'period': 6 },
        { code: 'FGA0039', displayName: 'MECÂNICA DE ESTRUTURAS AEROESPACIAIS', nature: 'OBRIGATORIO', alias: 'MDEA', 'period': 7 },
        { code: 'FGA0043', displayName: 'DINÂMICA DOS GASES PARA SISTEMAS AEROESPACIAIS', nature: 'OBRIGATORIO', alias: 'DDGPSA', 'period': 7 },
        { code: 'FGA0045', displayName: 'MECÂNICA DO VÔO', nature: 'OBRIGATORIO', alias: 'MDV', 'period': 7 },
        { code: 'FGA0148', displayName: 'ENGENHARIA DE SEGURANÇA DO TRABALHO', nature: 'OBRIGATORIO', alias: 'EDSDT', 'period': 7 },
        { code: 'FGA0048', displayName: 'MECÂNICA DO VOO ESPACIAL', nature: 'OBRIGATORIO', alias: 'MDVE', 'period': 8 },
        { code: 'FGA0050', displayName: 'DINÂMICA DE ESTRUTURAS AEROESPACIAIS', nature: 'OBRIGATORIO', alias: 'DDEA', 'period': 8 },
        { code: 'FGA0250', displayName: 'PROJETO INTEGRADOR DE ENGENHARIA 2', nature: 'OBRIGATORIO', alias: 'PIDE', 'period': 8 },
        { code: 'FGA0009', displayName: 'TRABALHO DE CONCLUSÃO DE CURSO 1', nature: 'OBRIGATORIO', alias: 'TDCDC', 'period': 9 },
        { code: 'FGA0021', displayName: 'ESTÁGIO SUPERVISIONADO', nature: 'OBRIGATORIO', alias: 'ES', 'period': 9 },
        { code: 'FGA0011', displayName: 'TRABALHO DE CONCLUSÃO DE CURSO 2', nature: 'OBRIGATORIO', alias: 'TDCDC', 'period': 10 }
    ])
}
