export default function handler(req, res) {
    res.status(200).json([
        { code: "FGA0161", displayName: "ENGENHARIA E AMBIENTE", nature: "OBRIGATORIO", alias: "EA", period: 1 },
        { code: "FGA0163", displayName: "INTRODUÃ‡ÃƒO Ã€ ENGENHARIA", nature: "OBRIGATORIO", alias: "IE", period: 1 },
        { code: "FGA0168", displayName: "DESENHO INDUSTRIAL ASSISTIDO POR COMPUTADOR", nature: "OBRIGATORIO", alias: "DIAPC", period: 1 },
        { code: "MAT0025", displayName: "CÃLCULO 1", nature: "OBRIGATORIO", alias: "C", period: 1 },
        { code: "CIC0004", displayName: "ALGORITMOS E PROGRAMAÃ‡ÃƒO DE COMPUTADORES", nature: "OPTATIVO", alias: "APDC", period: 1 },
        { code: "FGA0157", displayName: "PROBABILIDADE E ESTATÃSTICA APLICADO A ENGENHARIA", nature: "OBRIGATORIO", alias: "PEAE", period: 2 },
        { code: "IFD0171", displayName: "FISICA 1", nature: "OBRIGATORIO", alias: "F", period: 2 },
        { code: "IFD0173", displayName: "FISICA 1 EXPERIMENTAL", nature: "OBRIGATORIO", alias: "FE", period: 2 },
        { code: "MAT0026", displayName: "CÃLCULO 2", nature: "OBRIGATORIO", alias: "C", period: 2 },
        { code: "MAT0031", displayName: "INTRODUCAO A ALGEBRA LINEAR", nature: "OBRIGATORIO", alias: "IAL", period: 2 },
        { code: "FGA0084", displayName: "DESENVOLVIMENTO DE SOFTWARE", nature: "OPTATIVO", alias: "DDS", period: 2 },
        { code: "FGA0133", displayName: "ENGENHARIA ECONÃ”MICA", nature: "OBRIGATORIO", alias: "EE", period: 3 },
        { code: "FGA0158", displayName: "ORIENTAÃ‡ÃƒO A OBJETOS", nature: "OBRIGATORIO", alias: "OO", period: 3 },
        { code: "FGA0160", displayName: "MÃ‰TODOS NUMÃ‰RICOS PARA ENGENHARIA", nature: "OBRIGATORIO", alias: "MNPE", period: 3 },
        { code: "FGA0164", displayName: "HUMANIDADES E CIDADANIA", nature: "OBRIGATORIO", alias: "HC", period: 3 },
        { code: "FGA0071", displayName: "PRÃTICA DE ELETRÃ”NICA DIGITAL 1", nature: "OPTATIVO", alias: "PDED", period: 3 },
        { code: "FGA0073", displayName: "TEORIA DE ELETRÃ”NICA DIGITAL 1", nature: "OPTATIVO", alias: "TDED", period: 3 },
        { code: "FGA0085", displayName: "MATEMÃTICA DISCRETA 1", nature: "OPTATIVO", alias: "MD", period: 3 },
        { code: "FGA0108", displayName: "MATEMÃTICA DISCRETA 2", nature: "OBRIGATORIO", alias: "MD", period: 4 },
        { code: "FGA0138", displayName: "MÃ‰TODOS DE DESENVOLVIMENTO DE SOFTWARE", nature: "OBRIGATORIO", alias: "MDDDS", period: 4 },
        { code: "FGA0126", displayName: "FUNDAMENTOS DE ARQUITETURA DE COMPUTADORES", nature: "OBRIGATORIO", alias: "DADC", period: 4 },
        { code: "FGA0147", displayName: "ESTRUTURA DE DADOS E ALGORITMOS", nature: "OBRIGATORIO", alias: "EDDA", period: 4 },
        { code: "FGA0150", displayName: "PROJETO INTEGRADOR DE ENGENHARIA 1", nature: "OBRIGATORIO", alias: "PIDE", period: 4 },
        { code: "FGA0184", displayName: "GESTÃƒO DA PRODUÃ‡ÃƒO E QUALIDADE", nature: "OBRIGATORIO", alias: "GDPQ", period: 4 },
        { code: "FGA0003", displayName: "COMPILADORES 1", nature: "OBRIGATORIO", alias: "C", period: 5 },
        { code: "FGA0030", displayName: "ESTRUTURAS DE DADOS 2", nature: "OBRIGATORIO", alias: "EDD", period: 5 },
        { code: "FGA0137", displayName: "SISTEMAS DE BANCO DE DADOS 1", nature: "OBRIGATORIO", alias: "SDBDD", period: 5 },
        { code: "FGA0170", displayName: "FUNDAMENTOS DE SISTEMAS OPERACIONAIS", nature: "OBRIGATORIO", alias: "FDSO", period: 5 },
        { code: "FGA0172", displayName: "REQUISITOS DE SOFTWARE", nature: "OBRIGATORIO", alias: "RDS", period: 5 },
        { code: "FGA0173", displayName: "INTERAÃ‡ÃƒO HUMANO COMPUTADOR", nature: "OBRIGATORIO", alias: "IHC", period: 5 },
        { code: "FGA0060", displayName: "SISTEMAS DE BANCO DE DADOS 2", nature: "OBRIGATORIO", alias: "SDBDD", period: 6 },
        { code: "FGA0208", displayName: "ARQUITETURA E DESENHO DE SOFTWARE", nature: "OBRIGATORIO", alias: "ADDS", period: 6 },
        { code: "FGA0211", displayName: "FUNDAMENTOS DE REDES DE COMPUTADORES", nature: "OBRIGATORIO", alias: "FDRDC", period: 6 },
        { code: "FGA0238", displayName: "TESTES DE SOFTWARE", nature: "OBRIGATORIO", alias: "TDS", period: 6 },
        { code: "FGA0278", displayName: "QUALIDADE DE SOFTWARE 1", nature: "OBRIGATORIO", alias: "QDS", period: 6 },
        { code: "FGA0124", displayName: "PROJETO DE ALGORITMOS", nature: "OPTATIVO", alias: "PDA", period: 6 },
        { code: "FGA0109", displayName: "FUNDAMENTOS DE SISTEMAS EMBARCADOS", nature: "OBRIGATORIO", alias: "FDSE", period: 7 },
        { code: "FGA0210", displayName: "PARADIGMAS DE PROGRAMAÃ‡ÃƒO", nature: "OBRIGATORIO", alias: "PDP", period: 7 },
        { code: "FGA0244", displayName: "PROGRAMAÃ‡ÃƒO PARA SISTEMAS PARALELOS E DISTRIBUIDOS", nature: "OBRIGATORIO", alias: "PPSPD", period: 7 },
        { code: "FGA0112", displayName: "QUALIDADE DE SOFTWARE 2", nature: "OPTATIVO", alias: "QDS", period: 7 },
        { code: "FGA0115", displayName: "INFORMAÃ‡ÃƒO, COMUNICAÃ‡ÃƒO E A SOCIEDADE DO CONHECIMENTOS", nature: "OPTATIVO", alias: "ICSDC", period: 7 },
        { code: "FGA0242", displayName: "TÃ‰CNICAS DE PROGRAMAÃ‡ÃƒO EM PLATAFORMAS EMERGENTES", nature: "OPTATIVO", alias: "TDPEPE", period: 7 },
        { code: "FGA0021", displayName: "ESTÃGIO SUPERVISIONADO", nature: "OBRIGATORIO", alias: "ES", period: 8 },
        { code: "FGA0206", displayName: "ENGENHARIA DE PRODUTO DE SOFTWARE", nature: "OBRIGATORIO", alias: "EDPDS", period: 8 },
        { code: "FGA0240", displayName: "GERÃŠNCIA DE CONFIGURAÃ‡ÃƒO E EVOLUÃ‡ÃƒO DE SOFTWARE", nature: "OBRIGATORIO", alias: "GDCEDS", period: 8 },
        { code: "FGA0113", displayName: "FÃSICA PARA JOGOS ELETRÃ”NICOS 1", nature: "OPTATIVO", alias: "FPJE", period: 8 },
        { code: "FGA0009", displayName: "TRABALHO DE CONCLUSÃƒO DE CURSO 1", nature: "OBRIGATORIO", alias: "TDCDC", period: 9 },
        { code: "FGA0250", displayName: "PROJETO INTEGRADOR DE ENGENHARIA 2", nature: "OBRIGATORIO", alias: "PIDE", period: 9 },
        { code: "FGA0083", displayName: "APRENDIZADO DE MÃQUINA", nature: "OPTATIVO", alias: "ADM", period: 9 },
        { code: "FGA0111", displayName: "INTRODUÃ‡ÃƒO Ã€ WEB SEMÃNTICA", nature: "OPTATIVO", alias: "IWS", period: 9 },
        { code: "FGA0114", displayName: "FÃSICA PARA JOGOS ELETRÃ”NICOS 2", nature: "OPTATIVO", alias: "FPJE", period: 9 },
        { code: "FGA0011", displayName: "TRABALHO DE CONCLUSÃƒO DE CURSO 2", nature: "OBRIGATORIO", alias: "TDCDC", period: 10 },
        { code: "FGA0110", displayName: "COMPILADORES 2", nature: "OPTATIVO", alias: "C", period: 10 },
        { code: "FGA0273", displayName: "MELHORIA DE PROCESSOS DE SOFTWARE", nature: "OPTATIVO", alias: "MDPDS", period: 10 }
    ])
}
